# Generated by Django 5.2.9 on 2025-12-10 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(db_column='Author_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(db_column='Isbn', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title')),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'book_authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookLoans',
            fields=[
                ('loan_id', models.AutoField(db_column='Loan_id', primary_key=True, serialize=False)),
                ('date_out', models.CharField(db_column='Date_out')),
                ('due_date', models.CharField(db_column='Due_date')),
                ('date_in', models.CharField(blank=True, db_column='Date_in', null=True)),
            ],
            options={
                'db_table': 'book_loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('card_id', models.CharField(db_column='Card_id', primary_key=True, serialize=False)),
                ('bname', models.CharField(blank=True, db_column='Bname', null=True)),
                ('ssn', models.CharField(db_column='Ssn')),
                ('address', models.CharField(db_column='Address')),
                ('phone', models.CharField(blank=True, db_column='Phone', null=True)),
            ],
            options={
                'db_table': 'borrower',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('loan', models.OneToOneField(db_column='Loan_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='libraryApp.bookloans')),
                ('fine_amt', models.TextField(db_column='Fine_amt')),
                ('paid', models.BooleanField(db_column='Paid')),
            ],
            options={
                'db_table': 'fines',
                'managed': False,
            },
        ),
    ]
